# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160815_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
