# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160815_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='public/static/images'),
            preserve_default=False,
        ),
    ]
