# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='public/static/images'),
        ),
    ]
